baseURL = "https://www.prodexai.ru/"
languageCode = "ru"
title = "ProdEx — платформа управления интеллектуальной работой и ростом эффективности"

disableKinds = ["RSS", "taxonomy", "term"]

[params]
description = "ProdEx — российская платформа для управления интеллектуальным трудом, прозрачности командной работы и ускорения роста эффективности бизнеса."
keywords = "ProdEx, управление интеллектуальной работой, цифровая трансформация, эффективность бизнеса, продакт-менеджмент, управление изменениями, бизнес-процессы"
author = "ProdEx"
ogTitle = "ProdEx — платформа управления интеллектуальной работой"
ogDescription = "Превратите интеллектуальный труд в измеримый актив: ProdEx делает командное мышление прозрачным, воспроизводимым и управляемым."
ogLocale = "ru_RU"
ogSiteName = "ProdEx"
twitterCard = "summary"
twitterTitle = "ProdEx — интеллект под управлением"
twitterDescription = "Российская платформа для управления интеллектуальным трудом, цифрового следа и роста эффективности."
twitterCreator = "@ProdExTeam"
twitterSite = "@ProdExTeam"
faqURL = "https://www.prodexai.ru/#faq"

[params.organization]
name = "ProdEx"
url = "https://www.prodexai.ru/"
description = "ProdEx — платформа для управления интеллектуальной работой и роста эффективности бизнеса."
email = "info@prodexai.ru"
sameAs = [
  "https://t.me/ProdExTeam",
  "https://www.prodexai.ru/"
]
contactType = "sales"
areaServed = "RU"
availableLanguage = ["Russian"]

[params.website]
url = "https://www.prodexai.ru/"
name = "ProdEx"
alternateName = "ProdEx — интеллект под управлением"
description = "Платформа ProdEx помогает управлять интеллектуальной работой, фиксировать цифровой след и масштабировать эффективность бизнеса."
inLanguage = "ru"

[[params.faq]]
question = "С какими задачами помогает ProdEx?"
answer = "Платформа структурирует интеллектуальную работу, формирует цифровой след обсуждений и показывает, как инициативы влияют на эффективность бизнеса."

[[params.faq]]
question = "Сколько времени занимает запуск платформы?"
answer = "Базовое подключение и обучение команд занимают до двух недель: вы получаете готовые алгоритмы мышления, методические материалы и поддержку экспертов."

[[params.faq]]
question = "Можно ли интегрировать ProdEx с существующими системами?"
answer = "ProdEx открывает API и поддерживает обмен данными, чтобы передавать цифровой след интеллектуальной работы в BI-системы, HR-платформы и корпоративные порталы."
